### ISSUE TITLE
ver2.0 doesn't work with JP 6.7 update patch

### ISSUE THREAD

**Issue by Yuyuko-sama** [Lapig/PigPSO2Cam#15]
Nothing happend after u change those values and click set.
need help T T

**Comment by God-damnit-all** [comment]
@Lapig may have fixed it, try now.

Oddly enough there hasn't been any source code updates, though, which is concerning.

**Comment by Yuyuko-sama** [comment]
thx,it works now.

**Comment by Natanelt** [comment]
This still dont work for me
