### ISSUE TITLE
Insert button works to bring up menu, but stops working after transferring to base PSO2 lobby.

### ISSUE THREAD

**Issue by sorasin** [Lapig/PigPSO2Cam#2]
Sorry if this isn't the right place to thank you, but thank you so much for keeping this project alive. PSO2 being riddled with out of date mechanics and customizability your camera mod is a godsend.

As far as the issue goes, pretty much the title. I swap to base pso2 at least once a day to check things and as soon as I do that the insert key will no longer bring up the camera menu. It's not a huge issue as you can fix it by rebooting NGS but I just thought I'd bring it to your attention.

Cheers, and thanks again!

**Comment by Lapig** [comment]
I am aware of this, it's something I might get to at some point but I don't have a lot of interest in pso2classic at the moment and fixing it is somewhat nontrivial so for the time being you're going to be stuck with rebooting the game after switching to classic.

Thank you for submitting the issue though

**Comment by God-damnit-all** [comment]
@Lapig So is using this in PSO2 Classic at all just impossible now? I was hoping to use this for Challenge Miles runs.

**Comment by Lapig** [comment]
> @Lapig So is using this in PSO2 Classic at all just impossible now? I was hoping to use this for Challenge Miles runs.

Right, at the moment I have no plans for adding classic support
