### ISSUE TITLE
Is this legal?

### ISSUE THREAD

**Issue by sytoakira** [Lapig/PigPSO2Cam#5]
ive tried it and find it very useful and yet i was wondering if its ban able using this. Is there any way to know/verify?

**Comment by sytoakira** [comment]
I'm not looking for some sort of reassurance or guarantee that this is not ban able, its just looking at what this script do, does it break the ToS or something.

**Comment by Lapig** [comment]
No it's not "legal" but unless sega decides they want to specifically hunt down pigcam users you don't have anything to worry about, and in the almost year and a half it's been available sega hasn't seemed interested in doing that
